language: python
python:
- 2.6
- 2.7
- 3.3
- 3.4
- 3.5
- pypy
- pypy3
script:
- python setup.py sdist
- python setup.py bdist_wheel
deploy:
  provider: pypi
  user: cdumay
  password:
    secure: jRq58NHhFQ9k0PAtLqutV4l89ZHDrBtaJURIzpVUup6MDl22nZDBvZsAfR35rp/LK69vjLQx7w2GrXP4eAdQePjTaQXHfKE3c9EyAUshu8f0N5ooEklgDlNH1RmH3cnajmUzbWllpIzykyrnLJK0SAH5h60wWENTzGdDG6RCg5+QEjm0jc7BvCUkxE1owlPrkF2XUd+FLj8IsYV8WCBNBTkwpc+I5CNGyotletkNLjmggKPTN7hSAAagfN8wdNZSfVfh+UPtVGuFJJ4ql5ZsaEZ4h4+BreYFDMsQW/UjZ2jwFhClxHcmHlrAnFape+HRNk6VfnWvSAepLxoXzTMYJP8IGn6U5PBrWriDGFswSVpGtVTLifO3z5DpEYvjgSfRLeRDKSQ2jrWfpgjX9XCuaIGitMwN5T8sExtVQ0bk9cSqUkASm/PaNe3Z7oYnehf3UEslL6kp24d2dwrrMyTFJ/maBj2P5/1CkQiN/iJySRShhCCpu0WBgIRVWmqVO0ExgSGo+WAjW2ODyQjcAolu5A0nF72zGZpeilbRlbClmS+wq9O/rcwb7ofhodqAftY5f3M8VryScSckqsJly5eKD7kw1jwVWj/eaFFuNs1qckBpt7jUM1Q8KPwKplKI66LrjlvleZ1vpX86wXrXDimmfxsS64YzR/ibwMSji2GE6GI=
  on:
    tags: true
    distributions: sdist bdist_wheel
    repo: cdumay/flask-zookeeper
